### ISSUE TITLE
How to show BRScanResults total and receiptDate in UILabel.

### ISSUE THREAD

**Issue by ACS075** [BlinkReceipt/blinkreceipt-ios#10]
How to display scanned result data on UITextFiled and UILabel. I'm trying like this:
    self.expenseDateField.text = scannedResult.total;
    self.expenseDateField.text = scannedResult.receiptDate;
In **scannedresult** I'm getting data but when I'm trying to print **total** and **receiptDate** then there is object type value. Please help me how I can display amount and date in UILable and UITextfiled.

**Comment by dpanzer** [comment]
You need to use `total.value` and `receiptDate.value`
