### ISSUE TITLE
Not able to read receiptDate from receipt.

### ISSUE THREAD

**Issue by ACS075** [BlinkReceipt/blinkreceipt-ios#11]
I'm trying to scan a receipt but I'm not getting any value for **receiptDate** after scanning. I have gone through SDK and found that it is taking in this format **MM/dd/yyyy**.  How can I change the date format for **receiptDate**.

**Comment by dpanzer** [comment]
The SDK will look for dates in different formats depending on what you pass in `BRScanOptions.countryCode`. When a date is found it is returned as MM/dd/yyyy in `BRScanResults.receiptDate` and you can transform that as necessary. If you require further support please contact blinkreceipt@microblink.com
