### ISSUE TITLE
BRScanResults products and total not showing

### ISSUE THREAD

**Issue by fmappdev** [BlinkReceipt/blinkreceipt-ios#12]
I registered my key on dashboard, through pods i install blink SDK in app
All working fine but when i want to scan receipt then no result found
I am working in Swift4.2 with Xcode 10
This is my code 
 
func didFinishScanning(_ cameraViewController: UIViewController!, with scanResults: BRScanResults!) {
        cameraViewController.dismiss(animated: true, completion: nil)
        print(scanResults.products)
        print(scanResults.total)
    }

But nothing shown

**Comment by dpanzer** [comment]
Please contact blinkreceipt@microblink.com for support, thanks.
