### ISSUE TITLE
The library appears to include copies of some common Google files

### ISSUE THREAD

**Issue by mgod** [BlinkReceipt/blinkreceipt-ios#13]
The library includes copies of files that appear to be from the `GoogleSignIn` and `Firebase/Core` pods. I'm assuming these should instead be added to the pod dependencies and removed from the library source. I'm getting errors like:

```
objc[20168]: Class GIDAuthentication is implemented in both /private/var/[redacted]/BlinkReceipt.framework/BlinkReceipt ([redacted]) and /var/containers/[redacted]/MyAppName ([redacted]). One of the two will be used. Which one is undefined.
```

The following classes also show up:
```
GIDCallbackQueue
GIDGoogleUser
GIDProfileData
GIDAppSwitchScheme
GIDAppSwitchConfig
GIDRuntimeConfig
GIDRuntimeConfigFetcher
GIDScopes
GIDAuthFlow
GIDAuthenticationSession
GIDSignIn
GIDSignInButton
GIDSignInCallbackSchemes
GIDSignInInternalOptions
GIDSignInPreferences
GIDSignInStrings
GIDSignInWebView
GIDSignInWebViewController
GIDSignInWebViewURLProtocol
GIDTokenFetchDelegate
```

I've found some work arounds to avoid problems from this, but it's not clear if they'll continue to work in the future.

**Comment by dpanzer** [comment]
Hi @mgod this sounds like a known issue that was introduced when we attempted to enable bitcode support for our library. Apparently weak linking certain libraries into our SDK fails when it is built with bitcode in the sense that the symbols seem to get included in any client apps that incorporate the SDK even if the apps do not pull in these optional libraries (such as GIDSignIn). I believe if you force version 1.6.8 or below of our pod in your Podfile this will not be a problem.
