### ISSUE TITLE
App submission error with version 1.7.3

### ISSUE THREAD

**Issue by mgod** [BlinkReceipt/blinkreceipt-ios#14]
When submitting builds to Apple, we're getting alerted that:
```
The app contains or inherits from non-public classes in Frameworks/BlinkReceipt.framework/BlinkReceipt: MCOIMAPIdentity, MCOIMAPSearchExpression, MCOIMAPSession, MCOIndexSet, MCOMessageParser
```

**Comment by okankurtulus** [comment]
We are having the same issue

**Comment by dpanzer** [comment]
We will be updating our SDK today or tomorrow to sidestep this issue, although it remains unclear what exactly is getting flagged since those class names are certainly not conflicting with Apple private classes.
