### ISSUE TITLE
Error in CPU info building demo app

### ISSUE THREAD

**Issue by digivi13** [BlinkReceipt/blinkreceipt-ios#15]
I get the following errors when trying to run the BRDemo

Error in cpuinfo: sysctlbyname("hw.packages") failed: Operation not permitted
Error in cpuinfo: sysctlbyname("hw.cacheconfig") failed: Operation not permitted
2019-07-01 17:59:46.904587-0400 BRDemo[3019:698221] Metal GPU Frame Capture Enabled
2019-07-01 17:59:46.905530-0400 BRDemo[3019:698221] Metal API Validation Enabled
Error in cpuinfo: sysctl("HW_L3CACHESIZE") failed: Invalid argument

any suggestion as to how I might resolve? Our company is interested in integrating this sdk with our app

**Comment by dpanzer** [comment]
Hi @digivi13 are these errors causing the app to crash? I googled those errors and others report them as log messages that did not crash the app. In general you should email blinkreceipt@microblink.com so that we can provide better integration support if your company would like to trial our solution.

**Comment by digivi13** [comment]
The app does not crash, only a white screen appears. We are currently using the ABBYY receipt API in our app and were looking to compare performance of blink receipt for a possible switch.

**Comment by dpanzer** [comment]
Understood - I would advise to just follow the integration instructions here: https://blinkreceipt.github.io/blinkreceipt-ios/ rather than the bundled demo app. Please contact us by email if you need further support. We are confident our accuracy far exceeds ABBYY's solution!

**Comment by sejas** [comment]
@dpanzer I got same error:
I cannot run the demo app. The screen is white. It doesn't crash.
```
2019-08-01 12:23:56.690102+0100 BRDemo[61653:21361414] [DYMTLInitPlatform] platform initialization successful
Error in cpuinfo: sysctlbyname("hw.packages") failed: Operation not permitted
Error in cpuinfo: sysctlbyname("hw.cacheconfig") failed: Operation not permitted
2019-08-01 12:23:56.731398+0100 BRDemo[61653:21361284] Metal GPU Frame Capture Enabled
2019-08-01 12:23:56.731729+0100 BRDemo[61653:21361284] Metal API Validation Enabled
Error in cpuinfo: sysctl("HW_L3CACHESIZE") failed: Invalid argument
```

Maybe the error is with the license key "Test"?
`[BRScanManager sharedManager].licenseKey = @"Test";`

Thanks !

**Comment by dpanzer** [comment]
@sejas As I mentioned earlier, please follow the integration instructions at the link I provided. Of course "Test" is not a valid license key :)

**Comment by sejas** [comment]
I've Followed the steps and I still having the same issue.
What key should I use to test the demo app?
Thanks !

**Comment by dpanzer** [comment]
You can generate a demo license key at https://microblink.com/signup
