### ISSUE TITLE
For those with activation key trouble

### ISSUE THREAD

**Issue by digivi13** [BlinkReceipt/blinkreceipt-ios#16]
If you are trying to use the integration as described in the docs for blink receipt you will need to login as a developer on microblink and select the demo license key for BlinkInput (not blink receipt) When prompted below, select the version 2.x.x (not the version above 4.0). This string should have 8 blocks of 8 characters. Simply paste the string in your app delegate file as described in the docs and this API works beautifully. I did a direct comparison with ABBYY receipt capture API and the performance/accuracy was far superior and was able to work on device with ease.

**Comment by dpanzer** [comment]
Thanks for the tip and kind words @digivi13! I believe that currently this is resolved and you can select BlinkReceipt from the developer dashboard.
