### ISSUE TITLE
Support for reverting to full screen modalPresentationStyle on iOS 13

### ISSUE THREAD

**Issue by ApoorvKhatreja** [BlinkReceipt/blinkreceipt-ios#17]
iOS 13 switches to using `UIModalPresentationPageSheet` as the default style when presenting a view controller modally. 

On the latest iOS 13 betas, when BlinkReceipt is launched using `startStaticCameraFromController`, the camera is launched using a card page sheet style, which is not an ideal experience and not as immersive as a full screen presentation of the camera. Apple themselves have retained the full screen modal presentation style for the UIImagePickerController camera view. 

![IMG_0137](https://user-images.githubusercontent.com/143720/64452970-7ad5ca00-d0b5-11e9-9b85-c89e61548a75.PNG)

I would love to be able to either

- have full screen modal presentation be the default
- have control over the modal presentation style via the `BRScanOptions`

Thanks!

**Comment by dpanzer** [comment]
Hi @ApoorvKhatreja - yes we are aware of this. Our forthcoming update will set the `modalPresentationStyle` to full screen
