### ISSUE TITLE
Extremely slow initialization of custom camera

### ISSUE THREAD

**Issue by 51d4** [BlinkReceipt/blinkreceipt-ios#19]
I am trying to implement custom camera following the given guidelines. However, I have noticed that when I call `startCustomCamera(customController: BRCameraViewController, from: UIViewController, scanOptions: BRScanOptions, with: BRScanResultsDelegate)` there is an extremely long wait until the camera controller is displayed and view cycle method `viewDidLoad()` is triggered. On older devices (such as iPhone 5s) it can be as long as 15 seconds. However, when I try to call the `startStaticCamera(from: UIViewController, scanOptions: BRScanOptions?, with: BRScanResultsDelegate)`, the view presentation is instantaneous.

 Any idea what could be causing this delay or is this an expected behaviour?

**Comment by dpanzer** [comment]
Hi @51d4 - under the hood there is literally no difference between `startCustomCamera` and `startStaticCamera` except that in the latter case, we instantiate our own stock view controller (which is a subclass of `BRCameraViewController`) from the included nib and pass it forward to an internal function that prepares to scan, and in the former case, we take your view controller and pass it forward to the same internal function. So any discrepancy in loading time suggests something going on in your custom controller implementation

**Comment by 51d4** [comment]
@dpanzer I am not entirely convinced that this is the case because making my custom class conform to `UIViewController` instead of `BRCameraViewController` without any other changes causes no issues whatsoever with initialization time.

**Comment by dpanzer** [comment]
We can provide more in depth debugging in the context of a commercial relationship, please email blinkreceipt@microblink.com to discuss.
