### ISSUE TITLE
licenseKey

### ISSUE THREAD

**Issue by krutitrivedi** [BlinkReceipt/blinkreceipt-ios#2]
receive null scan result i think i m using "test" licenseKey so can you please provide guideline to create receipt licenseKey

**Comment by dpanzer** [comment]
Please visit https://microblink.com/signup to register a Microblink developer account. Once you have done that you'll need to create a license key for "BlinkInput" and then choose SDK version 4.0 when prompted below.

**Comment by krutitrivedi** [comment]
not working

**Comment by dpanzer** [comment]
Can you please email my colleague ivan.culo@microblink.com directly for help with getting a license key?
