### ISSUE TITLE
Demo Project not working on Xcode 11

### ISSUE THREAD

**Issue by zaidiabbas** [BlinkReceipt/blinkreceipt-ios#20]
Getting the following error when building the project on Xcode 11.

ld: '~blinkreceipt-ios-master/Demo/BRDemo/Pods/BlinkReceipt/BlinkReceipt.framework/BlinkReceipt' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '~blinkreceipt-ios-master/Demo/BRDemo/Pods/BlinkReceipt/BlinkReceipt.framework/BlinkReceipt' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by dpanzer** [comment]
Correct, bitcode is not supported currently
