### ISSUE TITLE
issue with installing via cocoapods.

### ISSUE THREAD

**Issue by AQElementary** [BlinkReceipt/blinkreceipt-ios#21]
I have tried multiple times to install this via cocoapods but unable to proceed although i have update my repo as well.

**Comment by AQElementary** [comment]
This library cocoa pod isnt installing ? Any help will be really appreciated ?

**Comment by dpanzer** [comment]
Please share your `Podfile`

**Comment by AQElementary** [comment]
pod 'BlinkReceipt', '~> 1.0'

**Comment by AQElementary** [comment]
I have tried  'BlinkReceipt' this too but giving issue. 
<img width="573" alt="Screenshot 2020-03-02 at 10 20 36 AM" src="https://user-images.githubusercontent.com/60500092/75647651-71e24180-5c6f-11ea-8377-1c561fab4f72.png">
<img width="755" alt="Screenshot 2020-03-02 at 10 20 51 AM" src="https://user-images.githubusercontent.com/60500092/75647658-77d82280-5c6f-11ea-8437-7085af475e29.png">

**Comment by dpanzer** [comment]
You are missing the 2 `source` lines at the beginning of your `Podfile`. See the first section of the README in this repo
