### ISSUE TITLE
No support available for Swift 

### ISSUE THREAD

**Issue by AQElementary** [BlinkReceipt/blinkreceipt-ios#22]
there is no support available for swift version. It ll be really better if any of swift version got available.

**Comment by dpanzer** [comment]
Hi @AQElementary - it is straightforward to use Obj-C frameworks inside Swift projects. You will find many tutorials for how to do this on the internet. We have clients that have been using our framework inside Swift projects with no issues for years.

**Comment by AQElementary** [comment]
Can you please share any link for swift example which has covered all Reciept scanning module ?

**Comment by dpanzer** [comment]
[BRSwiftDemo.zip](https://github.com/BlinkReceipt/blinkreceipt-ios/files/4268319/BRSwiftDemo.zip)

**Comment by AQElementary** [comment]
I dont know what i am missing but its also not working with me ? 

Here its all my screen shots taken of podfile, error showing, and pod install error as well.
<img width="756" alt="Screenshot 2020-03-02 at 10 19 57 AM" src="https://user-images.githubusercontent.com/60500092/75647599-48291a80-5c6f-11ea-8f89-71bf7aec5633.png">
<img width="573" alt="Screenshot 2020-03-02 at 10 20 36 AM" src="https://user-images.githubusercontent.com/60500092/75647602-4c553800-5c6f-11ea-8643-032d9af7a94c.png">
<img width="755" alt="Screenshot 2020-03-02 at 10 20 51 AM" src="https://user-images.githubusercontent.com/60500092/75647604-4cedce80-5c6f-11ea-9d4b-16c7e87d0d75.png">

**Comment by dpanzer** [comment]
You are missing the 2 `source` lines in the Podfile as specified in the first section of the README of this repo

**Comment by AQElementary** [comment]
Its still not installing ?
<img width="750" alt="Screenshot 2020-03-02 at 10 57 26 AM" src="https://user-images.githubusercontent.com/60500092/75649257-65141c80-5c74-11ea-8237-6aaee1a91978.png">
![Uploading Screenshot 2020-03-02 at 10.57.58 AM.png…]()

**Comment by dpanzer** [comment]
What is the error now when you run `pod install`

**Comment by AQElementary** [comment]
When i run the pod install command nothing happened although i waited for 30 mnts .
<img width="573" alt="Screenshot 2020-03-02 at 10 57 58 AM" src="https://user-images.githubusercontent.com/60500092/75649388-cb993a80-5c74-11ea-8b52-36d0e31a951b.png">

**Comment by dpanzer** [comment]
Well if you don't let Cocoapods finish how do you expect the BlinkReceipt framework to get downloaded? :)

You can look in the Cocoapods repository if you believe you are encountering some error that is preventing it from finishing. It might also be your internet connection. Please make sure to read documentation carefully before posting issues in this repository as the issue with missing `source` lines is documented in the very first section of this repository's README.

**Comment by AQElementary** [comment]
I have read already but its really strange .

After careful read the document now facing this issue 

<img width="573" alt="Screenshot 2020-03-02 at 11 10 47 AM" src="https://user-images.githubusercontent.com/60500092/75649903-4ca50180-5c76-11ea-8443-870904c72538.png">

**Comment by dpanzer** [comment]
I'm sorry but you appear to need a lot of help with basic iOS and Cocoapods usage. I recommend you spend some time Googling the various issues you are running into. I assure you there is no problem with our pod as we have many clients using it constantly. You might also try to simply follow the instructions of the on-screen prompts. It would appear that this issue with `AFNetworking` can be resolved by running the commands Cocoapods is suggesting to update your source repos.

**Comment by AQElementary** [comment]
Its installing now thanks for your help, And sorry for any inconvenience :)

**Comment by AQElementary** [comment]
Hey can you please share me any link for implementing this with Custom UI.
Its working fine but i want to load  BRCameraViewController in my custom
UIView. Any swift example if you can share will appreciated. Thanks

**Comment by dpanzer** [comment]
Building a custom camera controller is well documented here: https://blinkreceipt.github.io/blinkreceipt-ios/custom-camera-controller.html (which is also linked from this repository's README). This is not the appropriate forum to ask for help translating between Obj-C and Swift. This information is readily available by spending some time searching on the internet. You can email blinkreceipt@microblink.com and we will be happy to provide more in depth support in the context of a commercial relationship.

**Comment by AQElementary** [comment]
I understand and soon i will buy paid resources but for now i need a swift
example with Custom Controller for development purposes. Please provide me
that.

**Comment by dpanzer** [comment]
Unfortunately we cannot allocate time and resources to building a Swift custom controller sample for a non paying client. Again, the process for building a custom controller is well documented at the link I provided, and you will find many resources on the internet for translating between Obj-C and Swift.
