### ISSUE TITLE
Deprecated API Usage (UIWebview) - Apple will stop accepting submissions

### ISSUE THREAD

**Issue by lionserdar** [BlinkReceipt/blinkreceipt-ios#23]
After uploading the App to appstoreconnect, we receive this message:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.
The current version of the app has dependency on AFNetworking 3.0 which still has `UIWebview`.

More specifically `GTMOAuth2ViewControllerTouch`, `MSAuthenticationViewController` classes are using `UIWebview` s internally.

I believe that AFNetworking 4.0.0 has removed all UIWebView dependencies. Are you guys planning to update the current AFNetworking 3.0 to 4.0 or any other solutions ?

**Comment by dpanzer** [comment]
Hi @lionserdar, we already fixed the issue of `AFNetworking` including `UIWebView` classes by changing our pod's dependency to the subspec `AFNetworking/NSURLSession` (see here: https://github.com/BlinkReceipt/blinkreceipt-ios/blob/master/BlinkReceipt.podspec#L23)

As far as the internal dependencies of `GTMOAuth2ViewControllerTouch` and `MSAuthenticationViewController`, that is something we will have to look further into, as those are only used for our e-receipt functionality and we will have to evaluate whether substitutes exist that don't have those dependencies. I will keep you posted in this thread. Thanks for the heads up!

**Comment by lionserdar** [comment]
Thanks for the quick response. Still using the v 1.8.6 that why I missed that part. We will try to update our repo which will at least remove one of the `UIWebview` issues. We will look for an update on this thread.
