### ISSUE TITLE
Missing header

### ISSUE THREAD

**Issue by okankurtulus** [BlinkReceipt/blinkreceipt-ios#25]
Hi,
I recently updated from `1.7.4` to latest release, however i realised there are some files missing, like:
"BRAmazonManager.h"
"BREReceiptManager"
..

So what is the alternative usage for it? Can you please guide how we can proceed

**Comment by dpanzer** [comment]
Hi @okankurtulus, we have removed these files from the main pod for some time now. You can now find them in a separate pod called BlinkEReceipt, which is available here: https://github.com/BlinkReceipt/blinkereceipt-ios

**Comment by okankurtulus** [comment]
Great, thanks for support @dpanzer
