### ISSUE TITLE
Feature Request: Add upload option on sdk

### ISSUE THREAD

**Issue by geekrishabh** [BlinkReceipt/blinkreceipt-ios#26]
Hello @dpanzer 
Could you please add upload from the gallery option along with the camera capture?

**Comment by dpanzer** [comment]
Hi @GeekRishabh, we do not support scanning of arbitrary static images in the SDK unfortunately. In the context of a commercial relationship we can provide this functionality for debugging purposes only. If you would like to discuss that please email blinkreceipt@microblink.com. Thank you!
