### ISSUE TITLE
Can BlinkReceipt scan barcodes on receipts?

### ISSUE THREAD

**Issue by NSExceptional** [BlinkReceipt/blinkreceipt-ios#27]
I have yet to find a receipt ORC library or API that also scans and saves the barcode, which to me is the most important part of a receipt…

**Comment by dpanzer** [comment]
Hi @NSExceptional, yes as you can see in our docs, we do return barcodes: https://blinkreceipt.github.io/blinkreceipt-ios/Classes/BRScanResults.html#/c:objc(cs)BRScanResults(py)barcode

**Comment by NSExceptional** [comment]
Thanks!
