### ISSUE TITLE
Use the Cocoapods spec CDN in the demo podfile

### ISSUE THREAD

**Issue by NSExceptional** [BlinkReceipt/blinkreceipt-ios#28]
In the podfile, you have this line:

```ruby
source 'https://github.com/CocoaPods/Specs.git'
```

Change it to this:

```ruby
source 'https://cdn.cocoapods.org/'
```

Cocoapods has migrated away from hosting the spec repo on GitHub, they now use a CDN which is much faster for cloning and updating.

**Comment by dpanzer** [comment]
Done, thanks.
