### ISSUE TITLE
SDK does not include bitcode

### ISSUE THREAD

**Issue by NSExceptional** [BlinkReceipt/blinkreceipt-ios#29]
Just tried building the demo app and got an error about the BlinkReceipt framework not having been built with bitcode. You should include the bitcode so people using your SDK do not have to recompile their apps when a new phone with a new architecture comes out, such as arm64e.

**Comment by dpanzer** [comment]
We have some internal dependencies that were not built with Bitcode so this is not something that we can easily change. If this is a showstopper for you and you are a client or prospective client, please email blinkreceipt@microblink.com to discuss further.
