### ISSUE TITLE
This license is invalid for version 5.0

### ISSUE THREAD

**Issue by gurjnderSingh** [BlinkReceipt/blinkreceipt-ios#3]
I am getting the below issue on my console and I am using **DEMO License Key**.  How can I get version 4.2. I installed using the pod 'BlinkReceipt', '~> 1.0'.
This license is invalid for version 5.0. It is valid only for licensee 'My_Project_Bundle_Id', for product 'BlinkInput' on platform 'iOS' up to version 4.2. Please contact support for more information.
Can anyone let me know why I am getting this and How can I obtain version 4.2

**Comment by dpanzer** [comment]
Can you please email my colleague ivan.culo@microblink.com directly for help with getting a license key?

**Comment by gurjnderSingh** [comment]
> Can you please email my colleague [ivan.culo@microblink.com](mailto:ivan.culo@microblink.com) directly for help with getting a license key?

Ok. I have mailed.
Thanks!
