### ISSUE TITLE
Demo app doesn't do anything?

### ISSUE THREAD

**Issue by NSExceptional** [BlinkReceipt/blinkreceipt-ios#30]
Why is there a demo app if it's just a blank screen and no code?

Even if I were to add code and plug everything in, is the @"Test" license key going to work…?

**Comment by dpanzer** [comment]
Yes we are aware that the demo app is half-baked, sorry about that. We will get to it eventually. No the license key `Test` is not going to work. You would have to generate a demo license key at www.microblink.com/signup

**Comment by NSExceptional** [comment]
Gotcha, thank you! I'll keep my eye out for an updated demo app in the future
