### ISSUE TITLE
XCFramework Support

### ISSUE THREAD

**Issue by justinvallely** [BlinkReceipt/blinkreceipt-ios#33]
## Summary
With the introduction of M1 chips, Apple is shifting from "fat" frameworks to XCFrameworks and will soon require all packages to be shipped this way. Is this something Blink is actively working to support soon?

## OS version
Xcode 12+

## SDK installation method
Carthage, Cocoapods, SPM

**Comment by dpanzer** [comment]
Hi @justinvallely - this has been on our radar for a while. Unfortunately some of our 3rd party dependencies have been very slow moving in adding M1 support, notably even Google: https://github.com/firebase/firebase-ios-sdk/issues/7208

On our end we are ready to migrate to XCFrameworks as soon as possible!
