### ISSUE TITLE
Blink not giving response Neither in success nor i failure.

### ISSUE THREAD

**Issue by irfansaeed3** [BlinkReceipt/blinkreceipt-ios#35]
Hi,
I am working with the Blink SDK and successfully integrated it into my application and it was working for the last year. After updating to the new release 1.22.0, it stops working. 
When the application gives control to Blink for fetching the receipts, It does not give any response neither in success nor in failure.
Please help me to solve the problem.

**Comment by dpanzer** [comment]
@irfansaeed3 Can you clarify which methods you are calling in our SDK?

**Comment by irfansaeed3** [comment]
> @irfansaeed3 Can you clarify which methods you are calling in our SDK?
Hi, I am calling the Grab New orders method. You can see the code below.


 

### BRAccountLinkingManager.shared().grabNewOrders(for: linkedRetailer.toBlinkObject()) { [weak self] (retailer, scanResults, 
  ordersRemainingInAccount,  viewController, error )  in

            guard let self = self else { return }

            switch error {

            case .none:
                if let scanResults = scanResults {
                    let receipt = IHRReceipt(from: scanResults, linkedRetailer: linkedRetailer)
                    let blinkOutput = scanResults.blinkOutput()
                    IHRIHateReceiptsManager.logInfo(with: "\(logDescription) - SUCCESS with Blink output \(blinkOutput)")
                    IHRIHateReceiptsManager.logInfo(with: "\(logDescription) - SUCCESS with Receipt \(receipt)")
                    onSuccess((receipt, blinkOutput))
                } else {
                    IHRIHateReceiptsManager.logInfo(with: "\(logDescription) - NONE")
                    onSuccess(nil)
                }
                
            case .invalidCredentials, .noCredentials:
                IHRIHateReceiptsManager.logInfo(with: "\(logDescription) - FAILED with invalid credentials")
                self.unlink(retailer: linkedRetailer) {
                    onError(IHRError(with: error) ?? IHRError.invalidCredentials)
                }
                
            case .verificationNeeded:
                IHRIHateReceiptsManager.logInfo(with: "\(logDescription) - Verification needed")
                onVerificationNeeded(viewController)
                
            case .verificationCompleted:
                IHRIHateReceiptsManager.logInfo(with: "\(logDescription) - Verification completed")
                onVerificationCompleted()
                
            case .verificationCancelled:
                IHRIHateReceiptsManager.logInfo(with: "\(logDescription) - Verification cancelled")
                onVerificationCancelled()
                
            default:
                IHRIHateReceiptsManager.logInfo(with: "\(logDescription) - FAILED with \(error.stringValue)")
                onError(IHRError(with: error) ?? IHRError.failToParseLinkedAccountReceipts)
            }
            IHRIHateReceiptsManager.logInfo(with: "\(logDescription) - Remaining orders count \(ordersRemainingInAccount)")
            if ordersRemainingInAccount == 0 && error != .verificationNeeded && error != .verificationCompleted {
                // No need to call completion if .verificationNeeded or .verificationCompleted, the callback will be triggered again with .verificationCompleted, respectively .none
                onCompletion()
            }
        }
    }

**Comment by dpanzer** [comment]
Hi @irfansaeed3, that code looks fine although there isn't a lot of context. We'd be happy to debug further but this will involve passing test credentials. Please reach out to your account manager via email and we'll try to get to the bottom of this.
