### ISSUE TITLE
Missing Pods Libraries, i.e - dyld[9753]: Library not loaded: @rpath/

### ISSUE THREAD

**Issue by asifhabib** [BlinkReceipt/blinkreceipt-ios#36]
I am working on my custom private framework and I need to add the Blinkreceipts framework in my app, so I am adding the framework as a stand alone framework provide in the documents, But when I run my application there is following run time errors. 

**Error:** `dyld[21664]: Library not loaded: @rpath/AFNetworking.framework/AFNetworking`

I add the Pod` pod 'AFNetworking/NSURLSession', '~> 4.0'` then there was following runtime error. 

**Error:**  `dyld[21585]: Library not loaded: @rpath/CHCSVParser.framework/CHCSVParser`

I added the `pod 'CHCSVParser', '~> 2.1'` then there was following runtime error. 

**Error:** `dyld[21453]: Library not loaded: @rpath/GPUImage.framework/GPUImage`

I added the `pod 'GPUImage', '~> 0.1'` and then I had the following runtime error. 

**Error:** `dyld[9753]: Library not loaded: @rpath/MBProgressHUD.framework/MBProgressHUD`

I think pods are not embedded/copied in exported framework. Please update the exported framework. 

Thanks in advance.

**Comment by dpanzer** [comment]
Hi @asifhabib - rebundling our framework into your own framework is not a typical use case. We can provide more targeted support in the context of a commercial relationship. If you already have one, please contact your account manager. Otherwise please feel free to contact us here https://microblink.com/contact-commerce/

**Comment by asifhabib** [comment]
Ok, but even I add your framework in my application, it gives the same error.

**Comment by dpanzer** [comment]
When you are working with `BlinkReceiptStatic` and `BlinkEReceiptStatic` you must make sure that you add them to your target's list of "Frameworks, Libraries and Embedded Content" (under the General tab of target settings), and choose "Embed & Sign"

**Comment by asifhabib** [comment]
Same error. 
<img width="1388" alt="Screenshot 2022-04-06 at 11 28 50 PM" src="https://user-images.githubusercontent.com/3713433/162043695-653487d9-4d22-48ff-9f79-38a4df4f03a0.png">

**Comment by dpanzer** [comment]
Your error message indicates you are not actually using `BlinkReceiptStatic.framework`, you are using the Cocoapods version `BlinkReceipt.framework` which does not bundle dependencies

**Comment by dpanzer** [comment]
You need this: https://github.com/BlinkReceipt/blinkreceipt-ios/releases/download/1.27.0/BlinkReceiptStatic.xcframework-1.27.0.zip (and the equivalent for BlinkEReceipt)

**Comment by asifhabib** [comment]
Thanks @dpanzer
