### ISSUE TITLE
Manual Integration.

### ISSUE THREAD

**Issue by gurjnderSingh** [BlinkReceipt/blinkreceipt-ios#4]
I dont want to use cocoa pods. Is it possible to integrate it manually? I am integrating manually after adding BlickReceipt.framework it is crashing and showing the below error.

dyld: Library not loaded: @rpath/AFNetworking.framework/AFNetworking
  Referenced from: /private/var/containers/Bundle/Application/B33CB024-2060-4A59-BF47-51AE6EB53423/ReceiptScan.app/Frameworks/BlinkReceipt.framework/BlinkReceipt
  Reason: image not found.

Could you help me integrating it manually if possible?

**Comment by dpanzer** [comment]
Hello, please contact (or have someone from your company contact) blinkreceipt@microblink.com to discuss this.
