### ISSUE TITLE
Stitched Images

### ISSUE THREAD

**Issue by mattczech** [BlinkReceipt/blinkreceipt-ios#5]
I'm trying to get a stitched image of the scanned receipt following a scanning session. I've tried setting `returnStitchedImage` to `true` in `BRScanOptions`, but `BRScanResults.stitchedImage` is always `nil` in the delegate method `BRScanResultsDelegate.didFinishScanning(_:with:)`. Are there other options that need to be enabled to get this to work?

I'm using a custom controller UI with the following relevant code:

```
let options = BRScanOptions()
options.returnStitchedImage = true

BRScanManager.shared().startCustomCamera(CustomScanViewController(),
                                         from: self,
                                         scanOptions: scanOptions,
                                         with: self)
```

I'm using the latest version, 1.6.3.

Any help would be appreciated.

**Comment by dpanzer** [comment]
Hi Matt, the stitching feature is actually experimental and should not have made it into the headers. Sorry about that. We don't have any active plans to re-enable it, so for the moment if you want a stitched image you'll need to do it yourself using the individual frame images that are returned to you on disk. You need to set the `storeUserFrames` property of your `BRScanOptions` instance to `YES` and then look for the images after the scan session in `[BRScanManager sharedManager].userFramesFilepaths`
