### ISSUE TITLE
Not able to get receipt data

### ISSUE THREAD

**Issue by gurjnderSingh** [BlinkReceipt/blinkreceipt-ios#8]
I am using custom camera and using BRCameraViewController class. I am using self.manualCaptureSession = true and then set self.resumeScanning(). At take photo button action I did self.pauseScanning(). On Finish button action I call self.userFinishedScan() method. After that  it trigger call to didFinishScanning() method of BRScanResultsDelegate class. But here I got 0 products. I tried it with multiple receipts. Any help?

**Comment by dpanzer** [comment]
Hi @gurjindersinghkhalsa, a few questions:
-What device are you testing with?
-Did you sign up for a license key in our developer dashboard?
-Can you paste an image of one of the receipts you are trying to scan?

**Comment by gurjnderSingh** [comment]
> Hi @gurjindersinghkhalsa, a few questions:
> -What device are you testing with?
> -Did you sign up for a license key in our developer dashboard?
> -Can you paste an image of one of the receipts you are trying to scan?

Hi @dpanzer 
- I am using iPhone 6. 
- Yes, I have a valid license key.
- Yes. I am using valid receipt as got products when I startStaticCamera(). method.

Actually, It is working when I use startStaticCamera() method of BRScanManager() class then got products. But my requirement is to have a custom camera view. So, I am using BRCameraViewController().

Here is my code.
// Setting ScanOptions properties
  var objScanc: BRScanOptions?

    objScanc = BRScanOptions()
    objScanc?.storeUserFrames = true
    objScanc?.detectDuplicates = true
    objScanc?.detectLogo = true
    objScanc?.detectDistanceWithEdges = true

// Presenting Camera
 if let BRCameraViewCObj = UIStoryboard.init(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "BRCameraViewC") as? BRCameraViewC {
      BRScanManager.shared().startCustomCamera(BRCameraViewCObj, from: self, scanOptions: objScanc!, with: self)
    }

//  BRCameraViewC class
class BRCameraViewC: BRCameraViewController {
  override func viewDidLoad() {
    super.viewDidLoad()
    super.scanningRegion = CGRect.init(x: 27, y: 56, width: 320, height: 568)
    super.manualCaptureSession = true
    self.resumeScanning()
  }

@IBAction func tapTakePhoto(_ sender: UIButton) {
    self.pauseScanning()
}

@IBAction func tapFinish(_ sender: Any) {
    self.userFinishedScan() // It trigger calls to didFinishScanning() delegate of BRScanResultsDelegate. But here I got 0 products
  }
}

**Comment by dpanzer** [comment]
On certain devices (including iPhone 6) we do not actually process any frames except the ones the user has "snapped", which is accomplished by calling `userSnappedPhotoOnReady:` so I recommend that you modify your `tapTakePhoto` function to call that method instead of pausing, and put the call to `self.pauseScanning` inside the callback to the above method.

**Comment by gurjnderSingh** [comment]
> On certain devices (including iPhone 6) we do not actually process any frames except the ones the user has "snapped", which is accomplished by calling `userSnappedPhotoOnReady:` so I recommend that you modify your `tapTakePhoto` function to call that method instead of pausing, and put the call to `self.pauseScanning` inside the callback to the above method.

@dpanzer Thanks!
But Now application is started crashing on take photo action and having following reason
**Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'**

Here is my takePhotoAction

```
@IBAction func tapTakePhot(_ sender: UIButton) {
    self.userSnappedPhoto { (image, isBlur) in
      self.pauseScanning()
    }
}
```

Here is snap of thread call stack
![screen shot 2019-01-21 at 7 51 11 pm](https://user-images.githubusercontent.com/12212137/51480007-e7fe4e80-1db5-11e9-8b05-94ea8ba2003a.png)

**Comment by dpanzer** [comment]
Well one thing I would try is not to pause the session until you click Finish, maybe there is some race condition there. You might also try disabling the `manualCaptureSession` and commenting out all your calls to `resumeScanning` and `pauseScanning` just to see if you can get it working in the standard configuration

**Comment by gurjnderSingh** [comment]
> Well one thing I would try is not to pause the session until you click Finish, maybe there is some race condition there. You might also try disabling the `manualCaptureSession` and commenting out all your calls to `resumeScanning` and `pauseScanning` just to see if you can get it working in the standard configuration

I have disable manualCaptureSession and commenting all calls to `resumeScanning` and `pauseScanning`methods. But It is still crashing on calling `userSnappedPhotoOnReady:` method. Can you please share working example of custom camera?

**Comment by dpanzer** [comment]
We do not have a sample with a custom camera available. Please contact blinkreceipt@microblink.com and attach your sample project that demonstrates this crash, so we can try to reproduce and debug. Thanks!

**Comment by dpanzer** [comment]
By the way, we just saw a similar crash from one of our clients and the problem turned out to be that they (like your code above) was setting the `scanningRegion` property in absolute pixels rather than in percentages. See documentation here: https://blinkreceipt.github.io/blinkreceipt-ios/Classes/BRCameraViewController.html#/c:objc(cs)BRCameraViewController(py)scanningRegion

**Comment by gurjnderSingh** [comment]
> By the way, we just saw a similar crash from one of our clients and the problem turned out to be that they (like your code above) was setting the `scanningRegion` property in absolute pixels rather than in percentages. See documentation here: https://blinkreceipt.github.io/blinkreceipt-ios/Classes/BRCameraViewController.html#/c:objc(cs)BRCameraViewController(py)scanningRegion

Thanks!. It's working now.
